# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
dependencies: []

galaxy_info:
  min_ansible_version:  2.1
  author:       bmodotdev
  role_name:    docker
  description:  Install docker, docker-compose, and configure daemon.json
  license:      license (GPL-3.0-only)
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - docker
    - docker-compose
